twig:
  file_name_pattern: '*.twig'
  globals:
    app_locale: '%app_locale%'
    app_characterService: '@App\Service\Character\CharacterService'
    app_characterBonusService: '@App\Service\Character\CharacterBonusService'
    app_characterItemService: '@App\Service\Item\CharacterItemService'
    app_characterSpellService: '@App\Service\Spell\CharacterSpellService'
    app_characterQuestService: '@App\Service\Quest\CharacterQuestService'
    app_characterLevelService: '@App\Service\Character\CharacterLevelService'
    app_mapService: '@App\Service\Map\MapService'
    app_tradeService: '@App\Service\Trade\TradeService'

when@test:
  twig:
    strict_variables: true
