twig:
  file_name_pattern: '*.twig'
  globals:
    app_locale: '%app_locale%'
    app_characterService: '@App\Service\Character\CharacterService'
    app_characterBonusService: '@App\Service\Character\CharacterBonusService'
    app_characterItemService: '@App\Service\Item\CharacterItemService'
    app_characterSpellService: '@App\Service\Spell\CharacterSpellService'
    app_characterQuestService: '@App\Service\Quest\CharacterQuestService'

when@test:
  twig:
    strict_variables: true
