twig:
  file_name_pattern: '*.twig'
  globals:
    app_locale: '%app_locale%'
    app_itemService: '@App\Service\Item\ItemService'
    app_characterItemService: '@App\Service\Item\CharacterItemService'
    app_characterSpellService: '@App\Service\Spell\CharacterSpellService'
    app_characterBonusService: '@App\Service\Character\CharacterBonusService'
    app_characterLevelService: '@App\Service\Character\CharacterLevelService'
    app_characterReputationService: '@App\Service\Character\CharacterReputationService'
    app_dialogueService: '@App\Service\Dialogue\DialogueService'
    app_questService: '@App\Service\Quest\QuestService'

when@test:
  twig:
    strict_variables: true
