<?php

namespace App\DataFixtures\Character\Creature;

trait RevenantTrait
{
    const GHOST_CREATURES = [
        // Fantômes
        [
            'name' => 'Fantôme',
            'picture' => 'img/core/creature/fantome.png',
            'thumbnail' => 'img/core/creature/fantome_thumb.png',
            'description' => "<p>Une forme pâle flotte devant vous, les pieds juste au-dessus du sol… Sa tête penche sur le côté. Ses yeux vides vous fixent et semblent regarder à l'intérieur de vous.</p>",
            'strength' => 7,
            'dexterity' => 12,
            'constitution' => 10,
            'wisdom' => 14,
            'intelligence' => 12,
            'charisma' => 8,
            'healthMax' => 90,
            'manaMax' => 40,
            'fortune' => 0,
            'level' => 5,
            'race' => 'race_fantome',
            'reference' => 'creature_fantome',
        ],
        [
            'name' => 'Âme en peine',
            'picture' => 'img/core/creature/ame-en-peine.png',
            'thumbnail' => 'img/core/creature/ame-en-peine_thumb.png',
            'description' => "<p>Une forme pâle flotte devant vous, les pieds juste au-dessus du sol… Sa tête penche sur le côté. Ses yeux vides vous fixent et semblent regarder à l'intérieur de vous.</p>",
            'strength' => 7,
            'dexterity' => 12,
            'constitution' => 10,
            'wisdom' => 14,
            'intelligence' => 12,
            'charisma' => 8,
            'healthMax' => 90,
            'manaMax' => 40,
            'fortune' => 0,
            'level' => 5,
            'race' => 'race_fantome',
            'reference' => 'creature_ame-en-peine',
        ],
        [
            'name' => 'Gérome le Pendu',
            'picture' => 'img/chapter1/creature/gerome-le-pendu.png',
            'thumbnail' => 'img/chapter1/creature/gerome-le-pendu_thumb.png',
            'description' => "<p>Une forme spectrale, ou ce qui reste d'un homme, à la nuque tordue, flotte lentement au-dessus de la vase. Sa silhouette conserve les traces de sa pendaison&nbsp;: corde effilochée, peau violacée, regard brisé. Pourtant, dans ses yeux troubles, il reste une lueur… une mémoire incomplète.</p><p>Il ne semble pas hostile. Pas pour le moment, en tout cas.</p>",
            'strength' => 9,
            'dexterity' => 12,
            'constitution' => 12,
            'wisdom' => 15,
            'intelligence' => 13,
            'charisma' => 10,
            'healthMax' => 120,
            'manaMax' => 65,
            'fortune' => 0,
            'level' => 6,
            'race' => 'race_fantome',
            'reference' => 'creature_gerome_le_pendu',
        ],

        // Squelettes
        [
            'name' => 'Guerrier Squelette',
            'picture' => 'img/core/creature/squelette-guerrier.png',
            'thumbnail' => 'img/core/creature/squelette-guerrier_thumb.png',
            'description' => "<p>Ce squelette est celui d’un guerrier, son armure est rouillée et ses os sont fissurés. Il brandit une épée rouillée, prêt à se battre contre quiconque oserait s’approcher.</p>",
            'strength' => 8,
            'dexterity' => 10,
            'constitution' => 9,
            'wisdom' => 6,
            'intelligence' => 4,
            'charisma' => 3,
            'healthMax' => 60,
            'manaMax' => 0,
            'fortune' => 0,
            'level' => 4,
            'race' => 'race_squelette',
            'reference' => 'creature_guerrier_squelette',
        ],
        [
            'name' => 'Squelette de marin',
            'picture' => 'img/core/creature/squelette-de-marin.png',
            'thumbnail' => 'img/core/creature/squelette-de-marin_thumb.png',
            'description' => "<p>Ce squelette porte encore les lambeaux d’un uniforme marin. Sa cage thoracique est percée de part en part, comme si un harpon l’avait transpercée. Il se redresse lentement, l’arme toujours en main, animé par une haine que la mort n’a pas calmée.</p>",
            'strength' => 8,
            'dexterity' => 10,
            'constitution' => 9,
            'wisdom' => 6,
            'intelligence' => 4,
            'charisma' => 3,
            'healthMax' => 60,
            'manaMax' => 0,
            'fortune' => 0,
            'level' => 4,
            'race' => 'race_squelette',
            'reference' => 'creature_squelette_de_marin',
        ],
        [
            'name' => 'Squelette d’Eryl le Traître',
            'picture' => 'img/core/creature/squelette-deryl.png',
            'thumbnail' => 'img/core/creature/squelette-deryl_thumb.png',
            'description' => "<p>Le squelette d’Eryl se relève, son médaillon brille faiblement à son cou. Ses orbites vides semblent pleines de sarcasme et de mépris. Même dans la mort, son ambition le pousse à se battre comme un capitaine déchu.</p>",
            'strength' => 10,
            'dexterity' => 13,
            'constitution' => 11,
            'wisdom' => 8,
            'intelligence' => 6,
            'charisma' => 5,
            'healthMax' => 85,
            'manaMax' => 10,
            'fortune' => 0,
            'level' => 6,
            'race' => 'race_squelette',
            'reference' => 'creature_squelette_deryl',
        ],
    ];
}
