<?php

namespace App\DataFixtures\Character\Creature;

trait SauvageTrait
{
    const WILD_CREATURES = [
        // Rats
        [
            'name' => 'Gros rat',
            'picture' => 'img/core/creature/gros-rat.png',
            'thumbnail' => 'img/core/creature/gros-rat_thumb.png',
            'description' => "<p>Le rat est un animal nuisible qui se reproduit rapidement. Il est capable de transmettre des maladies et de causer des dégâts matériels. Il est important de s'en débarrasser rapidement.</p>",
            'strength' => 9,
            'dexterity' => 9,
            'constitution' => 8,
            'wisdom' => 7,
            'intelligence' => 10,
            'charisma' => 4,
            'healthMax' => 50,
            'manaMax' => 0,
            'fortune' => 0,
            'level' => 1,
            'race' => 'race_rat',
            'reference' => 'creature_gros_rat',
        ],
        [
            'name' => 'Rat géant',
            'picture' => 'img/core/creature/rat-geant.png',
            'thumbnail' => 'img/core/creature/rat-geant_thumb.png',
            'description' => "<p>Le rat est un animal nuisible qui se reproduit rapidement. Il est capable de transmettre des maladies et de causer des dégâts matériels. Il est important de s'en débarrasser rapidement.</p>",
            'strength' => 10,
            'dexterity' => 9,
            'constitution' => 10,
            'wisdom' => 7,
            'intelligence' => 12,
            'charisma' => 4,
            'healthMax' => 100,
            'manaMax' => 0,
            'fortune' => 0,
            'level' => 6,
            'race' => 'race_rat',
            'reference' => 'creature_rat_geant',
        ],

        // Loups
        [
            'name' => 'Loup affamé',
            'picture' => 'img/core/creature/loup.png',
            'thumbnail' => 'img/core/creature/loup_thumb.png',
            'description' => "<p>Un grognement rauque brise le silence. Entre les troncs, deux yeux jaunes brillent… et d’autres suivent dans l’ombre.</p>",
            'strength' => 11,
            'dexterity' => 13,
            'constitution' => 9,
            'wisdom' => 10,
            'intelligence' => 5,
            'charisma' => 5,
            'healthMax' => 70,
            'manaMax' => 0,
            'fortune' => 0,
            'level' => 3,
            'race' => 'race_loup',
            'reference' => 'creature_loup_affame',
        ],

        // Bouquetins
        [
            'name' => 'Bouquetin Féroce',
            'picture' => 'img/core/creature/bouquetin-feroce.png',
            'thumbnail' => 'img/core/creature/bouquetin-feroce_thumb.png',
            'description' => "<p>Son pelage est gris de poussière et ses cornes marquées par les années. Il vous fixe sans bouger, puis gratte le sol d’un sabot. Ici, c’est lui le maître des hauteurs.</p>",
            'strength' => 13,
            'dexterity' => 10,
            'constitution' => 14,
            'wisdom' => 6,
            'intelligence' => 4,
            'charisma' => 3,
            'healthMax' => 10,
            'manaMax' => 0,
            'fortune' => 0,
            'level' => 6,
            'race' => 'race_bouquetin',
            'reference' => 'creature_bouquetin_feroce',
        ],

        // Ours
        [
            'name' => 'Ours Cendré',
            'picture' => 'img/core/creature/ours-cendre.png',
            'thumbnail' => 'img/core/creature/ours-cendre_thumb.png',
            'description' => "<p>Son poil est couvert de poussière et ses cicatrices parlent de nombreux affrontements. L’Ours Cendré n’a peur de rien… sauf du feu.</p>",
            'strength' => 15,
            'dexterity' => 8,
            'constitution' => 16,
            'wisdom' => 5,
            'intelligence' => 4,
            'charisma' => 3,
            'healthMax' => 160,
            'manaMax' => 0,
            'fortune' => 0,
            'level' => 7,
            'race' => 'race_ours',
            'reference' => 'creature_ours_cendre',
        ],

        // Sangliers
        [
            'name' => 'Sanglier Noir',
            'picture' => 'img/core/creature/sanglier-noir.png',
            'thumbnail' => 'img/core/creature/sanglier-noir_thumb.png',
            'description' => "<p>Ses défenses sont aussi longues que des dagues, et sa course peut briser un bouclier. Le Sanglier Noir fonce sans réfléchir — sauf s’il sent le feuillage craquer sous vos pieds.</p>",
            'strength' => 14,
            'dexterity' => 9,
            'constitution' => 15,
            'wisdom' => 6,
            'intelligence' => 3,
            'charisma' => 2,
            'healthMax' => 130,
            'manaMax' => 0,
            'fortune' => 0,
            'level' => 5,
            'race' => 'race_sanglier',
            'reference' => 'creature_sanglier_noir',
        ],

        // Oiseaux
        [
            'name' => 'Corbeau des Brumes',
            'picture' => 'img/core/creature/corbeau-des-brumes.png',
            'thumbnail' => 'img/core/creature/corbeau-des-brumes_thumb.png',
            'description' => "<p>Étrangement silencieux, ce corbeau plane au ras du sol quand les brumes se lèvent. On dit qu’il annonce les malheurs… ou les provoque.</p>",
            'strength' => 6,
            'dexterity' => 14,
            'constitution' => 7,
            'wisdom' => 12,
            'intelligence' => 8,
            'charisma' => 10,
            'healthMax' => 40,
            'manaMax' => 0,
            'fortune' => 0,
            'level' => 2,
            'race' => 'race_oiseau',
            'reference' => 'creature_corbeau_des_brumes',
        ],
    ];
}
