<?php

namespace App\DataFixtures\Riddle\RiddleChoice\BoisDuPendu;

trait BosquetDesDruidesTrait
{
    const BOSQUET_DES_DRUIDES_RIDDLE_CHOICES = [
        [
            'position' => 1,
            'text' => "Je l’interroge sur ses intentions",
            'marker' => 'esprit',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_1',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_2',
            'reference' => 'riddle_choice_bosquet_des_druides_test_1_1',
        ],
        [
            'position' => 2,
            'text' => "Je me tiens prêt à me défendre",
            'marker' => 'force',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_1',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_2',
            'reference' => 'riddle_choice_bosquet_des_druides_test_1_2',
        ],
        [
            'position' => 3,
            'text' => "Je tends la main, en silence",
            'marker' => 'symbiose',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_1',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_2',
            'reference' => 'riddle_choice_bosquet_des_druides_test_1_3',
        ],
        [
            'position' => 4,
            'text' => "Je lui ordonne de s’écarter de mon chemin",
            'marker' => 'vanité',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_1',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_2',
            'reference' => 'riddle_choice_bosquet_des_druides_test_1_4',
        ],
        [
            'position' => 1,
            'text' => "Je cours vers le bruit, prêt à affronter ce qui s’y trouve",
            'marker' => 'force',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_2',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_3',
            'reference' => 'riddle_choice_bosquet_des_druides_test_2_1',
        ],
        [
            'position' => 2,
            'text' => "Je m’arrête et écoute pour en comprendre la source",
            'marker' => 'esprit',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_2',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_3',
            'reference' => 'riddle_choice_bosquet_des_druides_test_2_2',
        ],
        [
            'position' => 3,
            'text' => "Je m’approche lentement, en faisant partie du silence",
            'marker' => 'symbiose',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_2',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_3',
            'reference' => 'riddle_choice_bosquet_des_druides_test_2_3',
        ],
        [
            'position' => 4,
            'text' => "Je passe mon chemin. Ce n’est pas mon problème",
            'marker' => 'insouciance',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_2',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_3',
            'reference' => 'riddle_choice_bosquet_des_druides_test_2_4',
        ],
        [
            'position' => 1,
            'text' => "Je le soigne avec ce que j’ai",
            'marker' => 'symbiose',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_3',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_4',
            'reference' => 'riddle_choice_bosquet_des_druides_test_3_1',
        ],
        [
            'position' => 2,
            'text' => "Je mets fin à ses souffrances",
            'marker' => 'force',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_3',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_4',
            'reference' => 'riddle_choice_bosquet_des_druides_test_3_2',
        ],
        [
            'position' => 3,
            'text' => "Je médite un instant sur ce que sa blessure signifie",
            'marker' => 'esprit',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_3',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_4',
            'reference' => 'riddle_choice_bosquet_des_druides_test_3_3',
        ],
        [
            'position' => 4,
            'text' => "Je passe mon chemin, la vie est cruelle",
            'marker' => 'détachement',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_3',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_4',
            'reference' => 'riddle_choice_bosquet_des_druides_test_3_4',
        ],
        [
            'position' => 1,
            'text' => "Je le confronte directement. Il doit apprendre",
            'marker' => 'force',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_4',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_5',
            'reference' => 'riddle_choice_bosquet_des_druides_test_4_1',
        ],
        [
            'position' => 2,
            'text' => "Je cherche à comprendre pourquoi il ment",
            'marker' => 'esprit',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_4',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_5',
            'reference' => 'riddle_choice_bosquet_des_druides_test_4_2',
        ],
        [
            'position' => 3,
            'text' => "Je lui souris, et lui montre une autre voie sans le juger",
            'marker' => 'symbiose',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_4',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_5',
            'reference' => 'riddle_choice_bosquet_des_druides_test_4_3',
        ],
        [
            'position' => 4,
            'text' => "Je le gronde, c’est comme ça qu’on apprend",
            'marker' => 'autorité',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_4',
            'nextRiddleQuestion' => 'riddle_question_bosquet_des_druides_test_5',
            'reference' => 'riddle_choice_bosquet_des_druides_test_4_4',
        ],
        [
            'position' => 1,
            'text' => "Je refuse. L’équilibre prévaut",
            'marker' => 'symbiose',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_5',
            'reference' => 'riddle_choice_bosquet_des_druides_test_5_1',
        ],
        [
            'position' => 2,
            'text' => "Je l’accepte, pour faire le bien avec",
            'marker' => 'esprit',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_5',
            'reference' => 'riddle_choice_bosquet_des_druides_test_5_2',
        ],
        [
            'position' => 3,
            'text' => "Je le prends, je le mérite",
            'marker' => 'vanité',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_5',
            'reference' => 'riddle_choice_bosquet_des_druides_test_5_3',
        ],
        [
            'position' => 4,
            'text' => "Je détruis l’offrant, pour que personne d’autre ne puisse en profiter",
            'marker' => 'guerre',
            'riddleQuestion' => 'riddle_question_bosquet_des_druides_test_5',
            'reference' => 'riddle_choice_bosquet_des_druides_test_5_4',
        ],
    ];
}
