<?php

namespace App\DataFixtures\Item\MagicalWeapon;

trait OffensiveTrait
{
    const OFFENSIVE_MAGICAL_WEAPONS = [
        [
            'name' => 'Baguette de feu',
            'picture' => 'magical_wand.png',
            'description' => "<p>Petite et élégante, cette baguette est imprégnée de l’essence du feu. Elle permet à son porteur de projeter des boules de feu incandescentes, infligeant des dégâts aux ennemis sur une zone ciblée. Compacte et facile à manier, elle est idéale pour les mages débutants cherchant une arme offensive efficace.</p>",
            'type' => 'offensive',
            'price' => 250,
            'category' => 'category_magical',
            'chargeMax' => 25,
            'target' => 'health',
            'amount' => 10,
            'area' => 1,
            'reference' => 'magical_firewand',
        ],
        [
            'name' => 'Baguette de glace',
            'picture' => 'magical_wand.png',
            'description' => "<p>Cette baguette scintille d’un éclat glacial, ses gravures évoquant les vents hurlants des montagnes enneigées. Conçue pour lancer des boules de glace perçantes, elle ralentit les ennemis tout en infligeant des dégâts. Une arme précieuse pour ceux qui aiment contrôler leurs adversaires.</p>",
            'type' => 'offensive',
            'price' => 250,
            'category' => 'category_magical',
            'chargeMax' => 25,
            'target' => 'health',
            'amount' => 10,
            'area' => 1,
            'reference' => 'magical_icewand',
        ],
        [
            'name' => 'Baguette de foudre',
            'picture' => 'magical_wand.png',
            'description' => "<p>Fendue par des éclairs miniatures qui dansent autour d’elle, cette baguette canalise l’énergie de la foudre. Capable de lancer des éclairs rapides et précis, elle est redoutable contre les ennemis regroupés. Parfaite pour les mages recherchant rapidité et impact.</p>",
            'type' => 'offensive',
            'price' => 250,
            'category' => 'category_magical',
            'chargeMax' => 25,
            'target' => 'health',
            'amount' => 10,
            'area' => 1,
            'reference' => 'magical_stormwand',
        ],
        [
            'name' => 'Bâton de feu',
            'picture' => 'magical_stick.png',
            'description' => "<p>Plus puissant que la baguette de feu, ce bâton est orné de runes flamboyantes qui brillent dans l’obscurité. Il permet de lancer des boules de feu destructrices, infligeant des dégâts importants. Arme favorite des mages de combat, il est un symbole de destruction maîtrisée.</p>",
            'type' => 'offensive',
            'price' => 650,
            'category' => 'category_magical',
            'chargeMax' => 50,
            'target' => 'health',
            'amount' => 20,
            'area' => 3,
            'reference' => 'magical_firestick',
        ],
        [
            'name' => 'Bâton de glace',
            'picture' => 'magical_stick.png',
            'description' => "<p>Ce bâton glacé, entouré d’un halo de brume, amplifie la puissance des sorts de glace. Chaque boule de glace projetée par cet artefact transperce les défenses ennemies et fige leur élan. Un outil essentiel pour les mages tactiques aimant semer le chaos dans les rangs adverses.</p>",
            'type' => 'offensive',
            'price' => 650,
            'category' => 'category_magical',
            'chargeMax' => 50,
            'target' => 'health',
            'amount' => 20,
            'area' => 3,
            'reference' => 'magical_icestick',
        ],
        [
            'name' => 'Bâton de foudre',
            'picture' => 'magical_stick.png',
            'description' => "<p>Chargé d’électricité pure, ce bâton crépite en permanence, promettant une puissance dévastatrice. Avec sa capacité à projeter de puissants éclairs, il est une arme redoutée sur le champ de bataille. Les mages qui le manient s’imposent souvent comme des figures dominantes dans les combats.</p>",
            'type' => 'offensive',
            'price' => 650,
            'category' => 'category_magical',
            'chargeMax' => 50,
            'target' => 'health',
            'amount' => 20,
            'area' => 3,
            'reference' => 'magical_stormstick',
        ],
    ];
}
